### PR TITLE
chore: add deprecation warnings to all exported functions in deprecated sub-packages

### PR DESCRIPTION
**Pull request by adrianschmidt**

### CODE REVIEW

**Comment by jgroth** [comment]
Was just going to post a comment about build errors when I saw you had already fixed it :smile: :+1:

**Review by jgroth — DISMISSED** [review]
So many warnings :dizzy_face: :warning: :smile: 
warnings

**Comment by adrianschmidt** [comment]
> So many warnings 😵 ⚠️ 😄

Yeah, we should probably update our own packages sooner rather than later 😅

**Comment by adrianschmidt** [comment]
I'm testing this branch in some packages before squashing and merging.

**Pull request merged**
